# Built with Jekyll 2.5.3
#
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: ':title'

# Markdown
markdown: kramdown

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Setup
title:               'Caching and Naming'
tagline:             'We are bad at what we do!'
description:         ''
url:                 http://cachingandnaming.com
baseurl:             ''

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      type: post
      layout: post
      category: Ruby
